### ISSUE TITLE
Random User Account Created

### ISSUE THREAD

**Issue by tobsowo** [NerdbyteIO/FOSSBilling-CyberPanel#2] opened 2024-05-23 11:37 UTC
When a new user buys a hosting on Cyberpanel it is given a random account username 'example3' and also their First Name and Last Name are not passed. This is with an existing account, I have not tried for a new account created during checkout.

Also, I will like to know if a new user can be given a custom ACL based on what hosting plan they choose?

![image](https://github.com/NerdbyteIO/FOSSBilling-CyberPanel/assets/5642737/11016bf1-a76e-4a86-b15d-81b4ef372d64)

![CP](https://github.com/NerdbyteIO/FOSSBilling-CyberPanel/assets/5642737/2986dcdc-b969-4b3a-9b9f-8847ae29bd2a)

**Comment by jsonkenyon** [comment] 2024-05-23 11:44
Correct, when a user buys the hosting account we are just calling the createWebsite API call, this will also create the user account with no details.  Though if we should be creating a user account, I can get the code updated to do a create user with the details first then call the createWebsite perhaps.  Though it would still be coming through as a random username, as we pull this from FOSSBilling itself with 

`$account->getUsername()`

Which this makes the username some of the domain itself + a random number. 

For custom ACL that isn't in the coding at the moment, but it shouldn't be too hard to implement in a custom plan variable.  As of right now, we are just checking if they are a reseller and setting to ACL to reseller and if not a reseller they are a user.   I've got some running around todo here in a minute, but once I'm back I'll look into getting that custom ACL feature.

**Comment by tobsowo** [comment] 2024-05-23 11:52
All the suggestions works for me.
Thank you for implementing this plugin.

**Comment by tobsowo** [comment] 2024-05-23 12:10
I also noticed that all orders are attached to 'admin' as 'owner', so for every new hosting, it is owned by 'admin' which kind of give access to admin area when they login with the FOSSBilling generated login details especially updating the panel.

![image](https://github.com/NerdbyteIO/FOSSBilling-CyberPanel/assets/5642737/7a6cabb8-29ea-41f4-894e-a43cd5962586)

**Comment by tobsowo** [comment] 2024-05-23 12:35
> Correct, when a user buys the hosting account we are just calling the createWebsite API call, this will also create the user account with no details.  Though if we should be creating a user account, I can get the code updated to do a create user with the details first then call the createWebsite perhaps.  Though it would still be coming through as a random username, as we pull this from FOSSBilling itself with 
> 
> `$account->getUsername()`
> 
> Which this makes the username some of the domain itself + a random number. 

I agree with you, just confirmed this ordering with a new domain.

> For custom ACL that isn't in the coding at the moment, but it shouldn't be too hard to implement in a custom plan variable.  As of right now, we are just checking if they are a reseller and setting to ACL to reseller and if not a reseller they are a user.   I've got some running around todo here in a minute, but once I'm back I'll look into getting that custom ACL feature.

I think this will resolve, the issue I raised on the access to update the panel when the user ACL is changed.


Also, I tried to login to SSH using the credentials FOSSBiling shared via email but not working and checking CyberPanel it seems FTP account is not created automatically for each website.

**Comment by jsonkenyon** [comment] 2024-05-23 13:31
> I also noticed that if the same user orders for another hosting, it creates a new different website account in CyberPanel. I was thinking if it will be possible for a user to have a single account and can only add a new website based on the account limit?
> 
> Will it be possible to suspend/unsuspend such website under a user?

This should already be able to be done.  The API doesn't actually allow for suspending the actual user, but the website instead.  I could take a look and see if there can be something to make it so that the same user that already exists in CyberPanel can have multiple hosting accounts, and it be linked to the same user.


> Also, I tried to login to SSH using the credentials FOSSBiling shared via email but not working and checking CyberPanel it seems FTP account is not created automatically for each website.

Hmmm, the API docs don't have anything regarding SSH access, nor FTP access to tap into.  By default when you create the account manually does it actually generate the FTP account for you?  I know for other panels such as cPanel, SSH access, FTP access, isn't configured by default and would need to be enabled by the end-user of the hosting account. 

For context this is the API docs that I'm going off of, as you can see its rather limited in what it can actually do. https://cyberpanel.docs.apiary.io/#reference/server/login-as-user


For the owner and it giving access to the admin panel options, I did notice that, I thought that was by default.  This may actually be solved by creating the user account before the hosting plan.  That may actually fix this issue also, I'll take a look and do some testing and follow up.

**Comment by tobsowo** [comment] 2024-05-23 13:42
That works.
Thank you.

**Comment by jsonkenyon** [comment] 2024-05-23 14:57
@tobsowo I just pushed over an update, you can now overwrite the ACL by using a custom value in the package with ACL as the name.  (This doesn't overwrite for the reseller user however, only for the user)

I've also updated it so that it grabs the fullName of the user, and splits based on space, (May have to rethink this one) and grabs the parts and places them in the correct firstName,LastName so we are manually creating the user with the correct settings to match the FOSSBilling.

**Comment by jsonkenyon** [comment] 2024-05-23 15:00
Manually creating the user like we are now seems to fix it so that the user no longer see the admin panel.  This is a big WIN!  Thanks for reporting that @tobsowo

**Comment by jsonkenyon** [comment] 2024-05-23 15:07
I've also been looking to see if there is anyway to link up CyberPanel <=> FOSSBilling with the usernames, doesn't look like it.  Because FOSSBilling generates the username based on the domain itself, and CyberPanel doesn't allow looking up client details without the username, there is no way that I could link a current client to a new hosting plan.

**Comment by tobsowo** [comment] 2024-05-23 15:18
Let me create a ticket on this on CyberPanel.

**Comment by jsonkenyon** [comment] 2024-05-23 15:22
> Let me create a ticket on this on CyberPanel.

Sounds good, if they make it so that we can query on the email address that should work.  That should give us some options to grab the client details from the API.

**Comment by tobsowo** [comment] 2024-05-23 15:42
Is the email address also captured from FOSSBiling to CyberPanel?

**Comment by jsonkenyon** [comment] 2024-05-23 16:24
Yes, we can access the email address of the client.  This is included in the Server_Account, this holds client data, package data, etc.  So email address can be grabbed from that.

**Comment by tobsowo** [comment] 2024-05-23 16:28
That works.

**Comment by tobsowo** [comment] 2024-05-23 19:42
I just tested the latest version and can confirm that the ACL, contact details and the default port is working as expected but the owner is still admin which gives access to end users' ability to update the panel from their UI.

Also, I think in this case, the owner will now be the FOSSBilling User tied to their email so they can view all the website linked to them from one User account.

Since each website has it's own unique login, will a User also have a unique login that can view all website linked to the account?

**Comment by jsonkenyon** [comment] 2024-05-23 20:21
I'm not sure, I'll take another look.  I know that other hosting panels there is an owner of the client, that has control over that user, so a normal user shouldn't own their own user account.

For example if you're a reseller the owner of the new account that gets created under you, your reseller account should be the owner of that client account.  

The client account should only be an owner of their website account that is created.  

I'll take another look and confirm this, when I get back home.  However if you can provide a screenshot off the settings that the "user" shouldn't have this will be helpful in fully understanding the issue.  In my test lab, once manually creating the user account I wasn't able to see the admin functions anymore. 


For the last bit, not sure what you mean.  A client owns a hosting account and at the moment it seems that the API only allows one client => one website account, and they only put a unique value on the username, they don't care that the email is duplicated, which may be why they don't provide the email as an api endpoint to collect the client details.  So that one client should have access to that panel and able to add x amount of addon domains that they want and manage it all in that one account.

**Comment by tobsowo** [comment] 2024-05-23 21:23
I did not think about it that a client should not be able to have control over their own account and I totally agree with you.
Every other point you raised is fine by me just the manual user account creation I am still trying to understand, do I need to manually create users before FOSBilling link them?

**Comment by jsonkenyon** [comment] 2024-05-23 22:12
The code will automatically create the client using data from the FOSSBilling system. For instance, the function [createAccount](https://github.com/NerdbyteIO/FOSSBilling-CyberPanel/blob/main/CyberPanel.php#L93) calls a private function `createUserAccount()`, responsible for creating user accounts in CyberPanel. However, since usernames are generated based on domain parts and numbers in FOSSBilling, even existing CyberPanel clients will get new accounts linked to new hosting panels.

Essentially, one FOSSBilling client can have multiple CyberPanel client accounts linked to one hosting account. Each hosting account is tied to a unique username/password combination. This setup is due to the API endpoint limitations, preventing direct data retrieval based on usernames generated in FOSSBilling.

Therefore, while customers can manage all their hosting accounts in FOSSBilling, they can't do so in CyberPanel. FOSSBilling displays multiple hosting accounts, allowing users to log in to each respectively or manually.

**Comment by jsonkenyon** [comment] 2024-05-23 22:33
Perhaps the following diagram will help further explain?

![diagram](https://github.com/NerdbyteIO/FOSSBilling-CyberPanel/assets/16505105/8cb5da12-c33a-4e6b-bdc3-3c717888627e)

**Comment by jsonkenyon** [comment] 2024-05-23 23:17
Okay, so I also took a look and confirmed that it appears that "user" & "reseller" ACLs seem to be seeing stuff that they shouldn't.   However, this isn't an issue with the creation of the account by this server manager.  It's more of a upstream issue with CyberPanel and them allowing more permissions in the default ACLs.  The fix is going to be to overwrite the ACL with your custom one for reseller and user, so I'm going to also make it so that reseller can be overridden.

**Comment by tobsowo** [comment] 2024-05-23 23:44
Thank you for going extra miles to visualise the steps.
ACL works better to bypass the user having admin privileges.

**Comment by jsonkenyon** [comment] 2024-05-23 23:51
No problem, I've also made it so that the reseller ACL can be overridden.  This seems to be an upstream issue with CyberPanel allowing the user, and reseller ACLs that can't be edited to be allowed to see admin functions.  Perhaps they have expected you to create your own ACLs and not use the default ones. 

Though for now you can set the package custom value to the custom ACL(s) that you created to bypass this.  With that said, I think we are good to go with closing this one out also?

**Closed** 2024-05-24 03:30 UTC
Labels: enhancement

**Comment by tobsowo** [comment] 2024-05-24 07:37
Thank you very much.

**Comment by tobsowo** [comment] 2024-05-25 13:47
This is the response I got from CyberPanel 

```
Hello,

1. https://documenter.getpostman.com/view/2s8Yt1s9Pf?version=latest#1995ba90-d18d-4be7-8cd7-788f790747c5

here you can see modify user when you can change things for the user other than this we do not offer anything.

2. Changing the amount domain do you mean assigning the domain an other user?
```

**Comment by jsonkenyon** [comment] 2024-05-25 15:14
Taking a look at that, the only thing that they offer that could maybe be useful would be the fetch users, but I have no idea what all that details, most likely it would just return the username, which again wouldn't really be too helpful in our case as the username is generated on the fly by FOSSBilling, so it wouldn't match again.

**Comment by tobsowo** [comment] 2024-05-25 15:17
That's quite right.

**Comment by jsonkenyon** [comment] 2024-05-25 15:27
On this note, I think that their "clients" is just a really bad naming scheme.  Really, the way that I look at it is its "users".  Users shouldn't have any other information provided to it, but of course they do.  I'm assuming that is because they were planning to have it like this because they want you to use CyberPanel for all the things, that is cool and all.  But if you look at something like cPanel. 

They have multiple Users, and each user hold a hosting account.  So it would be the same setup as CyberPanel, just cPanel doesn't require all that information like address, etc they just care about the username + password.
